data: &data voc2012
model: &model resnet101
num_classes: 20
train_path: !join ['temp', *data, 'train.txt']
val_path: !join ['temp', *data, 'val.txt']
label_path: !join ['temp', *data, 'label.txt']

loss: BCElogitloss
optimizer: Adam
initmodel: ./initmodels/resnet101-5d3b4d8f.pth

batch_size: 32
scale_size: 640
crop_size: 576

num_workers: 8
max_epoch: 200
lr: 0.00001

topk: 3
threshold: 0.5

name: &name !cat [*data, *model]
log_dir: !join ['logs', *name]
ckpt_dir: &ckpt_dir !join ['checkpoints', *name]
ckpt_latest_path: !join [*ckpt_dir, 'latest_model.pth']
ckpt_best_path: !join [*ckpt_dir, 'best_model.pth']

output_dir: !join ['tmp', *name]